/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StationId = IDL.Text;
export const Time = IDL.Int;
export const BookingId = IDL.Nat;
export const UserId = IDL.Principal;
export const Booking = IDL.Record({
  'startTime' : Time,
  'bookingId' : BookingId,
  'endTime' : Time,
  'userId' : UserId,
  'stationId' : StationId,
  'portNumber' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addStation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [StationId],
      [],
    ),
  'bookSlot' : IDL.Func([StationId, IDL.Nat, Time], [BookingId], []),
  'cancelBooking' : IDL.Func([BookingId], [], []),
  'getAvailableSlots' : IDL.Func([StationId, Time], [IDL.Vec(Time)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StationId = IDL.Text;
  const Time = IDL.Int;
  const BookingId = IDL.Nat;
  const UserId = IDL.Principal;
  const Booking = IDL.Record({
    'startTime' : Time,
    'bookingId' : BookingId,
    'endTime' : Time,
    'userId' : UserId,
    'stationId' : StationId,
    'portNumber' : IDL.Nat,
  });
  
  return IDL.Service({
    'addStation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [StationId],
        [],
      ),
    'bookSlot' : IDL.Func([StationId, IDL.Nat, Time], [BookingId], []),
    'cancelBooking' : IDL.Func([BookingId], [], []),
    'getAvailableSlots' : IDL.Func(
        [StationId, Time],
        [IDL.Vec(Time)],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };